macro(rcc_strip_extension input output)
  get_filename_component(tmp ${${input}} NAME)
  string(FIND ${tmp} ".so" pos REVERSE)
  string(LENGTH ${tmp} len)
  if(${pos} EQUAL "-1")
    string(FIND ${tmp} ".a" pos REVERSE)
    if(NOT ${pos} EQUAL "-1")
        string(SUBSTRING "${tmp}" 0 ${pos} ${output})
    else()
      string(FIND ${tmp} ".lib" pos REVERSE)
      if(${pos} EQUAL "-1")
        if(RCC_VERBOSE_CONFIG)
          message(STATUS "Unable to find .so .a or .lib extension in ${${input}}")
        endif()
      else()
        string(SUBSTRING "${tmp}" 0 ${pos} ${output})
      endif()
    endif()
  else()
    string(SUBSTRING "${tmp}" 0 ${pos} ${output})
  endif()
endmacro()

macro(rcc_stip_lib input output)
    #if on linux
    string(SUBSTRING "${input}" "3" "-1" ${output})
endmacro()
