
if(NOT BUILD_DEPENDENCIES)
    find_package(RCC QUIET)
endif()
if(RCC_FOUND)
    message(STATUS "RCC found at: ${RCC_DIR} - ${RCC_INCLUDE_DIRS}")
else(RCC_FOUND)
    SET(IObject_INCLUDE "${CMAKE_CURRENT_SOURCE_DIR}/include")
    set(RCC_INCLUDE_DEPENDENCIES "${Boost_INCLUDE_DIRS};${CMAKE_CURRENT_LIST_DIR}/include")
    set(RCC_LIBRARY_DIRS_DEBUG "${Boost_LIBRARY_DIR};${Boost_LIBRARY_DIR_DEBUG};${CMAKE_BINARY_DIR}/Debug")
    set(RCC_LIBRARY_DIRS_RELWITHDEBINFO "${Boost_LIBRARY_DIR};${Boost_LIBRARY_DIR_DEBUG};${CMAKE_BINARY_DIR}/RelWithDebInfo")
    if(MSVC)
      set(RCC_COMPILE_FLAGS "/DBOOST_ALL_DYN_LINK")
    else()
      set(RCC_COMPILE_FLAGS "-DBOOST_ALL_DYN_LINK")
    endif()
    ADD_SUBDIRECTORY("dependencies/rcc")
    set_target_properties(RuntimeCompiler PROPERTIES FOLDER Dependencies)
    set_target_properties(RuntimeObjectSystem PROPERTIES FOLDER Dependencies)
endif(RCC_FOUND)
