#ifndef mo_objectplugin_LINK_LIBS_HPP
#define mo_objectplugin_LINK_LIBS_HPP

#if !defined(_WIN32)
  #define LINK_PREFIX "-l"
  #define LINK_POSTFIX ""
  #if !defined(NDEBUG)
    #if !defined(_DEBUG)
      #define _DEBUG
    #endif // !defined(_DEBUG)
  #endif // !defined(NDEBUG)
#else // !defined(_WIN32)
  #define LINK_PREFIX ""
  #dfine LINK_POSTFIX ".lib"
#endif // !defined(_WIN32)

#include "RuntimeObjectSystem/RuntimeLinkLibrary.h"
// both debug and release libraries

RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "pthread" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "boost_thread" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "boost_chrono" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "boost_date_time" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "boost_atomic" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "boost_fiber" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "boost_context" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "boost_system" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "boost_filesystem" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "cudart" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "boost_filesystem" LINK_POSTFIX);

#if defined(_DEBUG)
// Debug only libraries
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "mo_objectplugind" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "metaobject_objectd" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "metaobject_cored" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "RuntimeObjectSystemd" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "RuntimeCompilerd" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "metaobject_paramsd" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "metaobject_typesd" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "metaobject_runtime_reflectiond" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "gtestd" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "gtest_maind" LINK_POSTFIX);

#else // defined(_DEBUG)
// Release only libraries
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "mo_objectplugin" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "metaobject_object" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "metaobject_core" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "RuntimeObjectSystem" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "RuntimeCompiler" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "metaobject_params" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "metaobject_types" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "metaobject_runtime_reflection" LINK_POSTFIX);
RUNTIME_COMPILER_LINKLIBRARY(LINK_PREFIX "gtest" LINK_POSTFIX);

#endif

#undef LINK_PREFIX
#undef LINK_POSTFIX

#endif // mo_objectplugin_LINK_LIBS_HPP