macro(aq_install_python_test FILEPATH)
    if(TARGET aquila_python)
      get_filename_component( basename ${FILEPATH} NAME)
      add_custom_target(${basename} SOURCES ${FILEPATH})
      if(UNIX)
          configure_file(${FILEPATH} ${CMAKE_BINARY_DIR}/${basename} @ONLY)
      else()
          configure_file(${FILEPATH} Debug/${basename} @ONLY)
          configure_file(${FILEPATH} RelWithDebInfo/${basename} @ONLY)
          configure_file(${FILEPATH} Release/${basename} @ONLY)
      endif()
      install(FILES ${FILEPATH} DESTINATION ${CMAKE_INSTALL_PREFIX}/lib)
    endif()
endmacro()
